### ISSUE TITLE
SkipTest name are not escaped

### ISSUE THREAD

**Issue by coutin** [sh33dafi/jest-sonar#7]
**Describe the bug**
Currently if a test is skipped, the test name is not escape, and the xml generated won't be read by sonarqube. 

**To Reproduce**
Just have one test containing " inside his name, the xml generated won't be valid

**Expected behavior**
Those character should be escaped like for testname etc ...

**Desktop (please complete the following information):**
N/A

**Comment by tinovyatkin** [comment]
Probably got related error too:

```sh
15:48:56.168 ERROR: Error during SonarQube Scanner execution
Error during parsing of generic test execution report '/home/runner/work/engine/engine/reports/jest-reporter.xml'. Look at the SonarQube documentation to know the expected XML format.
Caused by: com.ctc.wstx.exc.WstxUnexpectedCharException: Illegal character ((CTRL-CHAR, code 27))
 at [row,col {unknown-source}]: [4,57]
	at com.ctc.wstx.sr.StreamScanner.throwInvalidSpace(StreamScanner.java:674)
	at com.ctc.wstx.sr.StreamScanner.throwInvalidSpace(StreamScanner.java:659)
	at com.ctc.wstx.sr.BasicStreamReader.parseAttrValue(BasicStreamReader.java:1918)
	at com.ctc.wstx.sr.BasicStreamReader.handleNonNsAttrs(BasicStreamReader.java:3139)
	at com.ctc.wstx.sr.BasicStreamReader.handleStartElem(BasicStreamReader.java:2968)
	at com.ctc.wstx.sr.BasicStreamReader.nextFromTree(BasicStreamReader.java:2839)
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1073)
	at org.codehaus.staxmate.in.SMHierarchicCursor.getNext(SMHierarchicCursor.java:79)
```
